### ISSUE TITLE
Test 1.14.12 checking if identifier is approved by the Registry needs to be removed.

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#24]
I've uploaded test file 1.12.13: ,http://stage.dataworkbench.io/view/dqf/files/2e1c4c7b-8a6c-4c8e-b6b8-d67ee60d865e?isTestfiles=true,The following warning message is returned:,Test 1.14.12 needs to be removed.

submitted via feedback button

**Comment by amy-silcock** [comment]
This is also the case for test 1.3.11

http://stage.dataworkbench.io/view/dqf/files/f5ae4602-2205-40e0-ba1f-fe0f40b4b65f?isTestfiles=true
