### ISSUE TITLE
Missing context information for 7.8.1

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#26]
Missing context info for financial info [in org file feedback](http://stage.dataworkbench.io/view/dqf/files/a1e4ead0f590c460d9c5948167190199)

![Screenshot from 2019-11-11 10-12-35](https://user-images.githubusercontent.com/223935/68575207-dcc2ff00-046b-11ea-8eaa-7f7b7c6092f9.png)

Also: message mentions "Activity", should be "Organisation"

**Comment by amy-silcock** [comment]
See: https://github.com/data4development/IATI-data-validator/issues/43

**Comment by amy-silcock** [comment]
See: https://github.com/data4development/IATI-data-validator/issues/40
