### ISSUE TITLE
Give user actual value causing error

### ISSUE THREAD

**Issue by YohannaLoucheur** [data4development/IATI-data-validator#40]
**Is your feature request related to a problem? Please describe.**
When the Validator indicates "The OECD DAC sector is invalid", it would be useful to have the actual value that is invalid instead of having to open the project in D-Portal, find the DAC sector section, then try to guess which sector is invalid. 

**Describe the solution you'd like**
After "The OECD DAC sector is invalid", add the sector(s) that cause the error (e.g. "sector 15172" or "sectors 15172, 15173"). 

**Describe alternatives you've considered**
Open D-Portal, see list of sectors coded in the project; open the IATI Standard codelist or the DAC sector codelist, check project code one by one to identify the culprit(s).

**Additional context**
The datastore API generates a list of errors with the specific "variable" that is problematic. However the output is JSON, which is not accessible to non-tech users.

**Comment by amy-silcock** [comment]
Linked to: https://github.com/data4development/IATI-data-validator/issues/48

**Comment by amy-silcock** [comment]
Context is now being shown for the sector code check. However, other tests are still lacking context, e.g. 2.1.4, 3.4.2, 9.80.1

**Comment by rolfkleef** [comment]
I've added that to a new issue #70
