### ISSUE TITLE
Provide export option 

### ISSUE THREAD

**Issue by YohannaLoucheur** [data4development/IATI-data-validator#41]
**Is your feature request related to a problem? Please describe.**
I wish I could export the Validator output. For example, one file has 76 instances where the DAC sector code is invalid; I would like to export the output (the 76 project identifiers) to an excel file, where I could add notes such as which code is invalid, what follow up is needed or done, who it's assigned to, etc.

**Describe the solution you'd like**
Add a csv export function.

**Describe alternatives you've considered**
Writing the project identifiers manually. Printing the Validator page or a screen capture.

**Comment by rolfkleef** [comment]
closing here (we do this as optional part of our service)
