### ISSUE TITLE
Validator requires policy marker - unclear why

### ISSUE THREAD

**Issue by YohannaLoucheur** [data4development/IATI-data-validator#42]
**Describe the bug**
In gac-amc-act_2_3.xml file, Validator flags 14 activites where it reports "The activity should also have a policy-marker using the OECD DAC vocabulary." then links to the guidance for coding sectors. At least one of these activities (CA-3-A032990001) provides 2 policy markers.

So:
- why is this activity flagged as missing a policy marker?
- why is a link provided to sector coding, which says nothing about policy marker?

**To Reproduce**
1. Go to Validator, type Global Affairs in org search field, open gac-amc-act_2_3.xml
2. Select warning related to policy markers
3. Scroll to 2nd activity, click on link to activity, scroll to bottom to see the policy markers
4. Back in Validator, click on "see guidance" next to the validator feedback and see that it leads to guidance on sector coding

**Expected behavior**
I expect the Validator to identify the policy markers in the activity data and not flag these as missing policy markers.
I expect the Validator to point to relevant guidance when data is indeed missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/6749013/68710766-2859d380-0566-11ea-8aef-5feca43456a3.png)

**Comment by amy-silcock** [comment]
The test should be removed - the IATI Standard **does not** state that other vocabularies should be used in addition to the 1: OECD DAC list.

It only says that if no vocabulary is specified, 1: OECD DAC is assumed.

**Comment by PetyaKangalova** [comment]
@amy-silcock  That is indeed correct. The policy marker does not follow the same rule for OECD DAC vocabulary as other elements. 

It is correct that if no vocabulary is specified, then OECD DAC is assumed: http://reference.iatistandard.org/203/activity-standard/summary-table/

Organisations can also use Vocabulary- 99 if no relevant codes on the policy marker codelist. In that case there should be a check about ` narrative must be present if @vocabulary=’99`’

**Comment by YohannaLoucheur** [comment]
Amy & Petya, this is useful clarification. However it does not address all the issues raised, such as:

- why is the Validator even requiring a DAC policy marker? Policy markers - DAC or otherwise - are not mandatory. 
- the guidance points to sector coding instead of policy marker coding

I would also flag that it is strange that the Validator would only flag this problem for 14 activities since we use policy markers in pretty much all our activities.

**Comment by amy-silcock** [comment]
Hi Yohanna, 

The test shouldn't be part of the validator. Removing it fixes all the issues you've raised on this ticket.

If you would like a further explanation please contact us on the support desk.

**Comment by amy-silcock** [comment]
The test has been removed. This looks good to me @rolfkleef
