### ISSUE TITLE
Warning Type 1 - using OECD DAC region vocabulary

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#45]
I check IOM data and got a warning message indicating that we should be using the OECD DAC region vocabulary.  I understand this is a warning and not an error but I question why this is a warning.  The OECD DAC region vocabulary, as I understand it, only has countries listed which are ODA recipients which, by definition, isn't a complete list of countries or regions.  We don't code to it because not all of our benefiting countries are ODA receiptents.  We go straight to the UN(M49) list.  ,If I have misunderstood the warning or the code list to which it refers please let me know,Reporter,: Michelle Levesque - IOM,E-mail,: ,mylevesque@iom.int

submitted via feedback button
USER-23

**Comment by amy-silcock** [comment]
This test should be removed. There is **no** 'should' in the Standard saying regions's should be declared in the Standard alongside OECD DAC ones.

It only says that if not vocabulary is present 1: OECD DAC is assumed. http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/recipient-region/

**Comment by amy-silcock** [comment]
The error has been resolved. This looks good to me @rolfkleef
