### ISSUE TITLE
Bug - USAID prefix not recognized as valid

### ISSUE THREAD

**Issue by DLakin01** [data4development/IATI-data-validator#47]
When checking any of our files with the new validator, we see a warning with the message that the IATI identifier given does not start with a known prefix, which appears to mean the system does not recognize "US-GOV-1" as a valid prefix. See screenshot:

![image](https://user-images.githubusercontent.com/28016495/68778794-a9b27400-0601-11ea-9c39-d708daa3a62c.png)

**Comment by amy-silcock** [comment]
@rolfkleef 1.14.8 is a test you added recently I believe: https://data4development.atlassian.net/jira/software/projects/VAL/boards/19?selectedIssue=VAL-257

I'm in favour or removing this test as I think you're comparing reporting-orgs to http://org-id.guide/. There will be times when an identifier is correct but org-id-guide is not up to date.

**Comment by YohannaLoucheur** [comment]
Glad to see this being discussed, as we have the same issue for our identifier CA-3, which does not conform to org-id.guide. 
As it is only a warning we were going to simply ignore it, but it would be preferable to remove it.

**Comment by rolfkleef** [comment]
To investigate... the system originally followed this hierarchy:

1. if its an approved publisher id in the Registry, it's ok
2. if not: if its on the [organisation identifier codelist](http://reference.iatistandard.org/203/codelists/OrganisationIdentifier/) it's ok
3. if not: if it doesn't start with an org-id prefix, provide this warning

**Comment by amy-silcock** [comment]
Linked to: https://github.com/data4development/IATI-data-validator/issues/50

**Comment by amy-silcock** [comment]
The prefix error has been resolved. This looks good to me @rolfkleef
