### ISSUE TITLE
Question: Org file validation - recipient country code is invalid

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#48]
I'm getting an error code for recipient country code however we don't even put recipient country code data in our file so I don't know how we are getting an error.  The only place we put country codes in our file is for documents.  Have I misunderstood something or could this be creating an erroneous error? ,Reporter,: Michelle Levesque - IOM,E-mail,: ,mylevesque@iom.int

submitted via feedback button
USER-25

**Comment by amy-silcock** [comment]
Hi Michelle,

The error is picking up that one country code is incorrect in your org file. This is within a document link, as the error message on the validator indicates.

![image](https://user-images.githubusercontent.com/27764077/68850925-d1224300-06cc-11ea-98dd-52d3b39b18e7.png)

The error is when you report Somalia. There is a blank space following the code which is causing the error.

![image](https://user-images.githubusercontent.com/27764077/68850893-bea80980-06cc-11ea-8c84-3b528aa02f24.png)

**Comment by PetyaKangalova** [comment]
Responded and clarified that the error is with the data. Issue is linked to another one on adding more information, so closing this one now.
