### ISSUE TITLE
Link back to validator from d-portal

### ISSUE THREAD

**Issue by notshi** [data4development/IATI-data-validator#49]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to link back to specific datasets from d-portal to the validator.

We currently have a link to the Registry from individual activities and would like to do the same to the validator.

**Describe the solution you'd like**
Currently, the validator does not use the ```slug``` name from the Registry in the url so we can't automatically generate links to the appropriate pages.

**Describe alternatives you've considered**
It doesn't have to be the main page - it could just be a redirect to your internal identifier so you don't have to change your current process.

**Additional context**
It would be **even nicer** if we could link to a specific activity and not just the dataset as this would be more helpful for people looking at the data.

**Comment by rolfkleef** [comment]
closing here (still a good idea)
