### ISSUE TITLE
Identifier does not start with a known prefix

### ISSUE THREAD

**Issue by Hlm1973** [data4development/IATI-data-validator#50]
**Bug (???) Description**
When testing our activity xml file, the new validator report the following warning :+1: 
"The identifier does not start with a known prefix.1.14.8 (see guidance)
In reporting-org FR-3", whereas FR-3 is the prefix for AFD.

**To Reproduce**
1. Go to "https://test-validator.iatistandard.org/"
2. Click on 'Check Data'
3. Click on 'Choose a file'
4. Select the attached file (unzip it before)
[AFD Activity file - IATI_Validator_Test.zip](https://github.com/data4development/IATI-data-validator/files/3864187/AFD.Activity.file.-.IATI_Validator_Test.zip)
5. Click on "Upload file"
6. Click on "Start validation"
7. Scroll down to 'Warnings'
8. Unselect all other Errors
9. See the message in Feedback

**Expected behavior**
Validator will accept the identifier FR-3 (AFD).

**Screenshots**
See the .png file.
![Validator_FR-3_Warning](https://user-images.githubusercontent.com/55181837/69153832-36b46c00-0adf-11ea-8afe-6ca21dfb56f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 entreprise 32bits
 - Browser : Chrome
 - Version 78.0.3904.97

**Comment by amy-silcock** [comment]
The prefix error has been resolved. This looks good to me @rolfkleef

**Comment by Hlm1973** [comment]
Thanks @rolfkleef ,
Warning no longer exists.
