### ISSUE TITLE
Narrative mandatory for reporting org own sector vocabulary

### ISSUE THREAD

**Issue by stormnl** [data4development/IATI-data-validator#51]
This warning is unexpected and seems to contradict the examples given on the standard page http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/sector/ 

<sector vocabulary="99" vocabulary-uri="http://example.com/vocab.html" code="A1" /> 

It looks like a rule has been added to the standard in the guidelines, that was not existing before. 
The demand to add a narrative is strange as the narrative is declared in the vocabulary uri. 

Suggest to go back to the original 2.03 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samuele-mattiuzzo** [comment]
@stormnl in the link you posted there's a snippet that is relevant to your feedback:

>... It is also recommended that if a publisher has its own classification system or systems then the vocabularies 99 or 98 (Reporting Organisation’s own vocabularies) should be used in addition to DAC codes.
Publishers using 98 or 99 must also include a narrative in the narrative element ...

This means that when a reporting org own vocabulary with code 98/99 is being published, then the narrative **must** be included, so I think the error you're receiving is actually being checked correctly.
 
To be confirmed by @PetyaKangalova / the BAs

**Comment by stormnl** [comment]
fine, than examples on the IATI standard page mislead new publishers as they do NOT contain a narrative.

**Comment by PetyaKangalova** [comment]
Hi Leo.  Thank you for flagging- we will fix the example on the below pages to be in line with the rule: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/sector/ and http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/sector/narrative/

**Comment by stormnl** [comment]
great, 
normal people follow examples and can't read a rule set.  ;-)

**Comment by rolfkleef** [comment]
closing here
