### ISSUE TITLE
critical error attribution

### ISSUE THREAD

**Issue by stormnl** [data4development/IATI-data-validator#52]
Oxfam Intermon has two activity files, one smaller and one larger, the second overlaps the first completely. 
The larger file get a significant number (± 50?) of 1 critical error.
The same activities in the smaller file do not trigger a similar critical error. 

- the number of error incidents is not clear, nor is clear in which activities it occurs (no purple sign in acitivies)
- the error code is very technical, not normal person language
- find it strange that the error doesn't occur in both files

**Comment by amy-silcock** [comment]
Hi @stormnl,

We expect non technical users not to be able to solve schema errors in their files. We recommend they pass the purple error message on to their technical colleagues or tool provider:
![image](https://user-images.githubusercontent.com/27764077/69350243-1ae0cf80-0c71-11ea-9d39-f8af56c590a5.png)

We will discuss how to word the purple critical error message better.

The data in the two files is different. The error is caused in the one file by the @secondary-reporter attribute is blank as per the purple error message: 
![image](https://user-images.githubusercontent.com/27764077/69350135-e2d98c80-0c70-11ea-8736-38014e532989.png)

Also, please can Oxfam Intermon remove the duplicate activities from their reporting.

**Comment by stormnl** [comment]
Hi Amy

Intermon just informed me that they corrected the file and removed the duplicated activity file
greetings
Leo

**Comment by PetyaKangalova** [comment]
Hi @stormnl . Thank you for the update! Looking at both activity files, it looks like the critical errors have been fixed in your files :) 

 Do let me know if you think there is any improvement we can make to the messaging for that specific error? If not, I will close this issue.

**Comment by stormnl** [comment]
Hi PetyaLeo here, any other text would be better than the text I got from the validator.GreetingsLeo  On Wed, 11 Dec 2019, 14:09 Petya Kangalova <notifications@github.com> wrote:Hi @stormnl . Thank you for the update! Looking at both activity files, it looks like the critical errors have been fixed in your files :)Do let me know if you think there is any improvement we can make to the messaging for that specific error? If not, I will close this issue.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rolfkleef** [comment]
We have this [on our internal list as well to look into it as a future enhancement](https://data4development.atlassian.net/browse/VAL-68). It's a bit tricky to find the right format. For now, we have chosen to say: your technical person should be able to generate that schema validation output using xmllint or similar. If they're unable to do that, maybe get in touch with someone who can do schema validation ;-)

**Comment by rolfkleef** [comment]
closing here
