### ISSUE TITLE
The IATI validator page gets juggled around on Internet Explorer v.11

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#54]
The text jumps around and difficult to read, and the "provide feedback" button doesn't allow for comments. ,Reporter,: IATI validator on Internet Explorer v.11,E-mail,: ,melinda.cuzner@sida.se

submitted via feedback button
USER-27

**Comment by PetyaKangalova** [comment]
Internet Explorer is no longer the recommended browser by Microsoft and its support is being [phased out](https://support.microsoft.com/en-gb/help/17454/lifecycle-faq-internet-explorer).

I got in touch with Melinda about this. She clarified that IE is indeed the standard browsers for Sida. But they can use other non-Microsoft browsers so it won't be a problem.  We will not be working on a fix for this issue, given the above.

**Comment by PetyaKangalova** [comment]
Closing the issue as per note on IE.
