### ISSUE TITLE
Org File - IOM

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#55]
I'm getting an error message 1x The recipient Country code is invalid.  ,We don't publish budgets by recipient countries so I don't know what this is referring to.  There isn't enough info in the error message to know what or where my error is.  ,this may be a duplicate but I could not figure out how to find previously submitted issues.  Sorry but Github is not my forté.,Reporter,: Michelle - IOM,E-mail,: ,mylevesque@iom.int

submitted via feedback button
USER-28

**Comment by PetyaKangalova** [comment]
Hi Michelle,
I just sent you a message directly :)

No error is showing currently on the validator for IOM's org file so it is difficult for me to investigate.
![image](https://user-images.githubusercontent.com/24607542/70621571-d01ffb00-1c11-11ea-8de7-3b9e06de4370.png)

**Comment by Michelle-IOM** [comment]
Just tried it and got a "congratulations" too.  We republished our Org file last week and tested it after we published.  Is there possibly a delay in the time between our publishing and when the validator reads the files that would explain it?  Either way, we appear to be ok now.

**Comment by PetyaKangalova** [comment]
Hi Michelle. I will close this issue now as it working. Once you have updated your data the validator will refresh within 24hours.
