### ISSUE TITLE
Usability :  color difference between errors and warnings

### ISSUE THREAD

**Issue by pelleaardema** [data4development/IATI-data-validator#57]
Color difference between errors and warnings: 
depending on the light and screen one is using, they resemble a lot! 

I would plea for a bigger difference (e.g. a lighter orange for warnings)

**Comment by PetyaKangalova** [comment]
Thanks for the feedback @pelleaardema ! We will look into as we review all proposals for improvements to the validator :)

**Comment by rolfkleef** [comment]
The colours were taken from the style guide https://styles.iatistandard.org/style-guide/colour but we can adapt.

**Comment by rolfkleef** [comment]
closing here
