### ISSUE TITLE
Usability : selecting error messages to be displayed

### ISSUE THREAD

**Issue by pelleaardema** [data4development/IATI-data-validator#58]
After deselecting an error message to see specific issues, then trying to select another error message in the navigation top-left, the validator selects a random error message (not the one I selected)

To reproduce: 
	• Open https://test-validator.iatistandard.org/view/dqf/files/8751fde27f9f94e3dd42e5564fa7c53f
	•  Deselect "The start of the period must be before the end of the period"
	• Then try to select it again

**Comment by PetyaKangalova** [comment]
Thanks for flagging. I have listed as a bug that needs to be looked at and fixed.


@rolfkleef 

I replicated the error. Once I have deselected 'The start of the period must be before the end of the period' and try to 'tick' it again I get the below:

![image](https://user-images.githubusercontent.com/24607542/70624204-b681b200-1c17-11ea-878f-1bae80bbeab9.png)

**Comment by amy-silcock** [comment]
Hi Rolf, this bug is still occuring. For example with 'the organisation type is invalid' http://test-validator.iatistandard.org/view/dqf/files/f9c1323c715fb81246cb2eb35ea2fe97

**Comment by rolfkleef** [comment]
Yes, this is still open and in the queue...

**Comment by rolfkleef** [comment]
This has been fixed in the latest version of the front-end

**Comment by PetyaKangalova** [comment]
Thanks for the update @rolfkleef .  I tested with a few publishers and looks like the bug has been fixed so closing the issue.
