### ISSUE TITLE
Validating identifiers

### ISSUE THREAD

**Issue by pelleaardema** [data4development/IATI-data-validator#59]
It is unclear how the validator checks identifiers:
Looking at [issue 47 ](https://github.com/data4development/IATI-data-validator/issues/47)(now closed), Rolf wrote:

_"To investigate... the system originally followed this hierarchy:
	1. if its an approved publisher id in the Registry, it's ok
	2. if not: if its on the organisation identifier codelist it's ok
	3. if not: if it doesn't start with an org-id prefix, provide this warning"_

However……there are a few issues here:
- Validating the data of [ACTIONAID INTERNATIONAL KENYA ](https://test-validator.iatistandard.org/view/dqf/files/4a58a7301047d5553cbe65a2853a280e)throws 5 types of warnings:
**1.3.13, 1.14.13, 1.8.13,1.10.13, 1.15.13 - The identifier must not contain any of the symbols /, &, | or ?.**

- Current [IATI guidance ](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/reporting-org/)indeed states that identifiers should not contain ?, &, | or ?. 
	reporting-org/@ref should match the regex [^\/\&\|\?]+ 
	
- ACTIONAID INTERNATIONAL KENYA is a [fairly new publisher](https://iatiregistry.org/publisher/about/aaik), however:
	ACTIONAID INTERNATIONAL KENYA
	Identifier: KE-NCB-OP/218/051/924/84
	HQ Country: Kenya
	**First published date:
	23 April 2019**
	
	Which means their IATI identifier was registered by the IATI secretariat **less than a year ago**.  So it meets criteria #1 in Rolfs logic. 
	(NOTE: There are currently ~25 publishers with an organisation id containing one or more forward slashes ("/"))

-  When I feed the validator non-existing identifiers (e.g. NL-XYZ-1234) it only gives a warning when this invalid value is present in 'reporting-org', not when it's in 'participating-org' 

**Solution:**
I would expect the validator to check for approved publisher ids

**Comment by PetyaKangalova** [comment]
Thanks @pelleaardema 
I am not sure I understand your last point. Could you clarify?

>When I feed the validator non-existing identifiers (e.g. NL-XYZ-1234) it only gives a warning when this invalid value is present in , not when it's in

Are you using the upload functionality and adding a reporting-org/@ref that is for an organisation that is not registered with IATI. If so, could you add screenshot of the error?

**Comment by pelleaardema** [comment]
Hi @PetyaKangalova 

Sorry, I used brackets which made the text disappear :-/

When I use a non-existing identifier (NL-XYZ-1234) in reporting-org, I get a warning (1.14.8 - The identifier does not start with a known prefix). This does not tell me if the check against existing identifiers took place.

I don't get that error message for the same identifier in 'participating-org'. Which I also would have expected --> that test appears to be missing.

**Comment by rolfkleef** [comment]
We'll investigate this again and add test cases and clarify the testing process further!

**Comment by rolfkleef** [comment]
I did a complete review of the identifier checks and added more test cases. [Here is a table](https://developer.data4development.nl/IATI-Rulesets/Identifier-checks.html) for now to document the checks and corresponding messages for all elements and attributes.

The new version still has to be deployed, the test scenarios [for organisation identifiers](https://github.com/data4development/IATI-Rulesets/blob/master/tests/iati/organisation-identifiers.xspec) and [for activity identifiers](https://github.com/data4development/IATI-Rulesets/blob/master/tests/iati/activity-identifiers.xspec) are online.

**Comment by rolfkleef** [comment]
closing here
