### ISSUE TITLE
Duplication Rules?

### ISSUE THREAD

**Issue by rbesseling** [data4development/IATI-data-validator#61]
Are 1.8.13 and 1.15.13 the same rule? 
	
Participating organisations: The identifier must not contain any of the symbols /, &, | or ?.
Basic organisation information: The identifier must not contain any of the symbols /, &, | or ?.

**Comment by PetyaKangalova** [comment]
@rbesseling  thanks for the feedback!

- 1.15.13 checks for  `receiver-org/@ref`
- 1.8.13 checks for `participating-org/@ref`

There is also another one 1.10.13 that checks for `provider-org/@ref`

@rolfkleef please can you cross-check that as well?
@rbesseling  , would you be able to add a screenshot of the activity you were looking at? Just wondering if we can make the messaging clearer/more specific.

**Comment by rbesseling** [comment]
Hi Petya, 

Please see error message below: 

https://test-validator.iatistandard.org/view/dqf/files/ec126c36dbd6a7238e4e013b25faf2cd

**Comment by rolfkleef** [comment]
Actually, the second category should be "Financial information". The test is the same, the category is supposed to help users find where to fix it (e.g. in which Aidstream section). (Which was your idea, @rbesseling :-)) -- will fix the cateogy

**Comment by rbesseling** [comment]
Thanks Rolf!

**Comment by amy-silcock** [comment]
Hi @rolfkleef checking this one and the warning now does not flag for the file (warning should occur for participating and receiver org): https://test-validator.iatistandard.org/view/dqf/files/0004abe02aaeef3a1c1d59908e3f19b4. 

The identifier with the / in it is still being reported by ActionAId UK https://aidstream.s3.us-west-2.amazonaws.com/xml/aauk-activities.xml

![image](https://user-images.githubusercontent.com/27764077/72265980-55ce0680-3615-11ea-8043-e519869eca94.png)

However, in other activities it is flagging and is now doing so in the correct category :) e.g. https://test-validator.iatistandard.org/view/dqf/files/ee244fbfe887155a0601f7ca6c82daa8

**Comment by amy-silcock** [comment]
The above is answered with logic in this table: https://developer.data4development.nl/IATI-Rulesets/Identifier-checks.html

KE-NCB-OP/218/051/924/84 is a approved identifier on the IATI Registry.

**Comment by PetyaKangalova** [comment]
Just tested again and error messages are working as expected in the correct category.
