### ISSUE TITLE
Overview of Activities in Validator

### ISSUE THREAD

**Issue by rbesseling** [data4development/IATI-data-validator#66]
Does not identify which activity this refers to. "Congratulations! This IATI file has successfully passed validation with no errors!"

It feels strange that 'good quality' IATI activities are not shown when check an organisations activity file. I would rather be able to see all activities so that we can still click through to D-Portal and check activitiy manually.

**Comment by PetyaKangalova** [comment]
Thanks for the suggestion @rbesseling ! It will be  great to hear from other users and whether they would find this useful.

**Comment by rbesseling** [comment]
Hi Petya,

Here is an example where one of the activities is 'good' but then underneath it gives warning messages. I think this would confuse the user. It also doesn't say which activity is 'good'. 

Also, I would still want to be able to do a manaul check in D-Portal to make sure no errors were missed. 

Example: https://test-validator.iatistandard.org/view/dqf/files/ec126c36dbd6a7238e4e013b25faf2cd

**Comment by rolfkleef** [comment]
closing here
