### ISSUE TITLE
Target Value Warning

### ISSUE THREAD

**Issue by rbesseling** [data4development/IATI-data-validator#67]
Currently no error/warning message is given if there is no Target Unit defined.

**Comment by PetyaKangalova** [comment]
@rbesseling  which[ attribute for target ](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/result/indicator/period/target/)are you referring to? Do you mean the @value?

Could you add an example? 

Thank you!

**Comment by rbesseling** [comment]
Hi Petya, 

Here is an example of a result indicator with actual values and no target values. There a few other examples if you want some more :-)

Example: http://d-portal.org/ctrack.html?publisher=DK-CVR-36980214#view=act&aid=DK-CVR-36980214-Dutch-2016-2020-SouthSudan

**Comment by amy-silcock** [comment]
Hi @rbesseling I'm not aware of there being any must or should in the standard that says you have to include a target element. The example you've provided has no target element in the xml, which means d-portal presents it as 'undefined%'.

**Comment by rolfkleef** [comment]
closing here
