### ISSUE TITLE
Comment: Default flow type, aid type and tied status missing, but they are populated in AidStream

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#68]
I received the following warnings for Catholic Relief Service's activities US-EIN-13-5563422-6870213 and US-EIN-13-5563422-8040632.,The default flow type is missing. (6.2.4) ,The default aid type is missing. (6.2.6) ,The default tied status is missing. (6.2.7) ,However, these fields are populated in AidStream. 

submitted via feedback button
USER-29

**Comment by PetyaKangalova** [comment]
Hi there,
There was no email added in the feedback form so I am contacting you directly here.
Checking Cathloc Relief Services' data now, I don't get any errors as the ones listed above: https://test-validator.iatistandard.org/view/dqf/files/cb77887ad843dcb67f80923ae75f79c4
 Can you let me know if you are still getting the same error and please add a link/screenshot.

You should be able to add or change the default flow type, aid type ad tied status on Aidstream.

Let us know if we can help with anything else.

**Comment by rolfkleef** [comment]
closing here
