### ISSUE TITLE
Context info for messages missing

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#70]
tests are still lacking context, e.g. 2.1.4, 3.4.2, 9.80.1

**Comment by rolfkleef** [comment]
additional context info and tests have been added

**Comment by PetyaKangalova** [comment]
Tested 2.1.4- fixed.
Tested 3.4.2- fixed.
![image](https://user-images.githubusercontent.com/24607542/82212013-c1005000-9909-11ea-929f-0f31409ab9cb.png)

Tested 9.80.1- fixed.
![image](https://user-images.githubusercontent.com/24607542/82212412-6f0bfa00-990a-11ea-87e2-26ce8a736c4e.png)
