### ISSUE TITLE
(Tech Team) Review warning and error messaging

### ISSUE THREAD

**Issue by amy-silcock** [data4development/IATI-data-validator#71]
**Describe the bug**
The wording of the errors and warnings could be made more consistent. For example: https://github.com/data4development/IATI-data-validator/issues/56

IATI Tech Team to review and suggest changes.

**Comment by PetyaKangalova** [comment]
All reviewed and updated as per the [Master testing sheet.](https://docs.google.com/spreadsheets/d/1KqyMHRfbnCS0sTQspTm1cPm-HCsnV-SkshqK7aAMUVg/edit#gid=1164167513)
