### ISSUE TITLE
Allow for URL to fetch xml

### ISSUE THREAD

**Issue by relyd** [data4development/IATI-data-validator#72]
Online generated XML would be easier to (re)validate with allowing for an URL as datasource. 

A re-validate option would be easy to have, so if you fix an error/warning, you can quickly retest. 

Currently the workflow might be a bit tedious : create xml, download XML, upload to validator, validate, fix errors and once again.

**Comment by PetyaKangalova** [comment]
Thank you for your feedback and apologies for the delayed response.

As I understand, you are referring to the "Check data" option in the validator. 

![image](https://user-images.githubusercontent.com/24607542/74924096-c7923080-53c9-11ea-864a-8efaa0548d48.png)
Currently you have the "upload" data functionality. The D4D team is in the process of implementing a **second option** for that page, where you can just **add a URL** where the XML file is based.  I believe that is what you are requesting and it will become available before the validator is being launched.

**Comment by analystcmyk** [comment]
Yes correct, thank you.

**Comment by rolfkleef** [comment]
closing here (has been included in the delivery)
