### ISSUE TITLE
The planned start date must be before the planned end date.

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#73]
Regarding our activity file, 2 elements raise error regarding their planned dates.,But the 2 projects (FR-3-CKE105301 & FR-3-CMA113301) have the following dates :,Planned Start date : 2014-04-14 / 2012-11-02,Planned End date : 2019-12-18 / 2019-07-17,So, for me, there is a "bug" in the validator.,KR,,Hervé

submitted via feedback button
USER-30

**Comment by PetyaKangalova** [comment]
Thank you for your feedback. Would you be able to provide a link to the validator or a screenshot of the error message so that I can replicate the error?  It is difficult to comment without more information.

**Comment by rolfkleef** [comment]
closing here
