### ISSUE TITLE
Page not displaying

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#74]
I'm getting a blank screen, both on Chrome and Explorer. This seems to be just for me, colleagues are seeing the page as normal. Do my settings need changing? ,Reporter,: Odeta,E-mail,: ,odeta.butkute@beis.gov.uk

Location,: ,https://test-validator.iatistandard.org/validate,User-Agent,: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; rv:11.0) like Gecko,Screen Resolution,: 1536 x 864
submitted via feedback button
USER-31

**Comment by PetyaKangalova** [comment]
I have emailed the user directly to check if the error still exist and get additional information.

**Comment by rolfkleef** [comment]
closing here
