### ISSUE TITLE
time zone

### ISSUE THREAD

**Issue by cgarboni** [data4development/IATI-data-validator#75]
**Describe the bug**
When checking a newly created XML on the test-validator.iatistandard.org, the error:
"The last-updated-datetime of the organisation must not be in the future" occurs.
This is just because, probably the time is tested agains GMT time.

**To Reproduce**
1. create an IATI XML file
2. test it within the hour (CET time) and you get the error mentioned above. One hour later the error disapears. 

**Expected behavior**
not shown as an error.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: MS Edge

**Comment by PetyaKangalova** [comment]
@cgarboni  thank you for your feedback and apologies for the delay in responding. Would you be able to add a screenshot of the error?  Are you using the "[Check data](https://test-validator.iatistandard.org/validate)"?

In the meantime, @rolfkleef , can we check how the test is set for the "last-updated-datetime" ?

**Comment by rolfkleef** [comment]
The validator runs on UTC. If a publisher does not include timezone information in the last-updated-datetime value, the value is assumed to be in the timezone of the validator.

I've added tests to the ruleset to verify this: https://github.com/data4development/IATI-Rulesets/commit/0918b6e5af15181e68386b5c8c5afc0b48a4fe29

**Comment by PetyaKangalova** [comment]
Thanks @rolfkleef for adding the additional test on timezone. I don't think many organisations specify timezone in their file and I am not sure how best to test this. The rule in IATI refers to the date, which is key here. Can we briefly speak about the test you have added this afternoon?

```
@last-updated-datetime
The last date/time that the data for this specific activity was updated. This date must change whenever the value of any field changes.
This value must be of type xsd:dateTime.
@last-updated-datetime must not be more recent than the current date
```

**Comment by PetyaKangalova** [comment]
Tested with the below and happy for additional checks on timezone to remain. Tests are in line with current IATI rules.  As organisations use the validator it will be good to hear their feedback and how often timezones are specified in the XML file.

```
<?xml version="1.0" encoding="utf-8"?>
	   <iati-activities version="2.03" generated-datetime="2020-02-20T02:21:36">
       <iati-activity last-updated-datetime=""2020-05-18T14:49+01:00""



```
