### ISSUE TITLE
The process validation is never ending.

### ISSUE THREAD

**Issue by taufik-hidayat** [data4development/IATI-data-validator#76]
We run a looping task to process the validation for all dataset with the endpoint from "Addhoc validation and feedback" in Postman. And we got some process is never-ending for example for this XML https://static.data.gouv.fr/resources/donnees-de-laide-au-developpement-de-lafd-1/20191217-112421/fr-afd-id-2019-12-13.xml. But this incident is not consistent, sometimes is just working if I try again the validation to the same XML.

**Comment by PetyaKangalova** [comment]
@rolfkleef can you look into this one and respond to Taufik? I am unclear if this is currently a bug or not.

**Comment by rolfkleef** [comment]
closing here
