### ISSUE TITLE
Missing IATI Registry packages for People in Need

### ISSUE THREAD

**Issue by markbrough** [data4development/IATI-data-validator#82]
**Describe the bug**
For the People in Need organisation (`pin`), there are currently 11 datasets on the IATI Registry:
https://iatiregistry.org/publisher/pin

However, the test IATI validator lists only 5 datasets:
https://test-validator.iatistandard.org/organisation/pin

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the IATI Registry link above for People in Need
2. See that there are 11 datasets.
3. Go to the IATI validator link above for People in Need
4. See that there are 5 datasets

**Expected behaviour**
On the IATI Validator, show all 11 datasets as on the IATI Registry

**Comment by rolfkleef** [comment]
closing here
