### ISSUE TITLE
DAC 5 Digit Sector code 12196 being flagged as invalid

### ISSUE THREAD

**Issue by lucasfog1** [data4development/IATI-data-validator#83]
Hello, the  validator is giving me the following error:

"The OECD DAC sector is invalid.9.76.1 (see guidance)
For value 12196"

However, 12196 is is on the codelist ( https://iatistandard.org/en/iati-standard/203/codelists/sector/ ).

Is this a validator bug or is the codelist out of date?

Many thanks for your help!

**Comment by matmaxgeds** [comment]
It is also marked as active on the codeforiati version in case that helps: https://codelists.codeforiati.org/Sector/#12196

**Comment by PetyaKangalova** [comment]
@lucasfog1  thank you for flagging and I can confirm that this is indeed a [valid sector code](https://iatistandard.org/en/iati-standard/203/codelists/sector/ ) so you can continue using it. I'll flag this with our developers to investigate why an error has occurred in the validation report and to make sure the codelist checks on the validator are done with the most recent version of the codelist.

We are still in testing phase but plan to launch the IATI validator at the end of Septemeber, so your feedback is much appreciated: https://iativalidator.iatistandard.org/

Please do raise any future issues directly into this repository: https://github.com/IATI/IATI-Validator-Web

**Comment by lucasfog1** [comment]
@PetyaKangalova Thanks a lot for confirming. I've noted the repository to use if I encounter any future issues. Looking forward to the much anticipated launch!

**Comment by nosvalds** [comment]
Hi @lucasfog1 this has been fixed with version 1.6.3 of the IATI-Validator-Actual which has just been released to production. 

https://github.com/IATI/IATI-Validator-Actual/releases/tag/1.6.3
